url:             http://www.pablocantero.com/
assets_base_url: http://www.pablocantero.com/assets/

# Dependencies
highlighter: rouge
redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'strikethrough', 'superscript', 'with_toc_data']

permalink: /blog/:year/:month/:day/:title/

# Setup
title:            'Pablo Cantero'
tagline:          'Coding all the things'
description:      ''

author:
  name:           'Pablo Cantero'
  url:            https://twitter.com/pablocantero

paginate:         999

# Custom vars
version:          2.1.0

github:
  url:           https://github.com/phstc

twitter:
  url:           https://twitter.com/pablocantero

linkedin:
  url:           https://linkedin.com/in/pablocantero

rss:
  url:           http://feeds.feedburner.com/pablocantero

comments: true

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
