# Dependencies
markdown:         redcarpet
extensions:       [fenced_code_blocks]
highlighter:      pygments


# Permalinks
# permalink:        pretty
permalink: /blog/:year/:month/:day/:title
relative_permalinks: true

# Setup
title:            'Pablo Cantero'
tagline:          'Coding all the things'
description:      ''
url:              http://www.pablocantero.com/
baseurl:          /

author:
  name:           'Pablo Cantero'
  url:            https://twitter.com/pablocantero

paginate:         999

# Custom vars
version:          2.1.0

github:
  url:           https://github.com/phstc

twitter:
  url:           https://twitter.com/pablocantero

linkedin:
  url:           https://linkedin.com/in/pablocantero

comments: true
